spring.application.name=practicalaboralsql

spring.datasource.url=jdbc:h2:file:./data/database
# spring.datasource.url=jdbc:h2:mem:dbtest
spring.datasource.username=satoshi
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# JWT Configuration
app.jwt.secret=muchosAñosDespuesFrenteAlPelotonDeFusilamientoElCoronelAurelianoBuendiaRecordariaElDiaEnQueSuPadreLoLlevoAConocerElHielo
# 24 horas en milisegundos
app.jwt.expiration=86400000

spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# spring.jpa.defer-datasource-initialization=true
# spring.sql.init.mode=always
# spring.sql.init.schema-locations=classpath:sql/triggers.sql

spring.h2.console.enabled=true