spring.application.name=practicalaboralsql

# spring.datasource.url=jdbc:h2:file:./data/database
spring.datasource.url=jdbc:h2:mem:dbtest
# spring.datasource.username=satoshi
# spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# logging.level.org.hibernate=DEBUG
# logging.level.org.hibernate.tuple=DEBUG

# logging.level.org.springframework.web=DEBUG
# logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true